os:
  - linux
  - osx

# need due bug on homebrew see:
#   https://changelog.travis-ci.com/xcode-11-3-1-xcode-11-2-1-xcode-11-1-and-xcode11-images-updated-142286
osx_image: xcode11.4

language: c

before_install:
  # ccache hacks. see: https://github.com/travis-ci/travis-ci/issues/5383
  #Install ccache on osx
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  #Fix ccache for clang
  - if [ "$CC" = "clang" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export CFLAGS="-Qunused-arguments"; else CFLAGS=""; fi

addons:
  apt:
    packages:
      - libnl-3-dev
      - libgcrypt11-dev
      - zlib1g-dev
      - libsqlite3-dev
      - libpcap-dev
      - libssl-dev
      - libnl-genl-3-dev
      - libpcre3-dev
      - lcov
      - libcmocka0
      - libcmocka-dev
      - libhwloc-dev
      - clang-format-3.8
  homebrew:
    packages:
      - ccache
      - cmocka
      - libpcap
      - libgcrypt
      - openssl
      - pcre
      - sqlite3
    #update: true

compiler:
  - gcc
  - clang

script: |
  ./build/travis-format.sh Style "Checking source code style..." ./build/travis-formatting.sh &&
  ./build/travis-format.sh GCrypt "Building with GCrypt..." ./build/gcrypt.sh &&
  ./build/travis-format.sh OpenSSL "Building with OpenSSL..." ./build/openssl.sh &&
  ./build/travis-format.sh Dist "Creating a dist tarball and then building from it..." ./build/dist_check.sh &&
  exit 0

cache: ccache
